<?php
  $wrapperTag = $this->wrapperTag ?? 'div';
  $wrapperClass = 'dropdown'; // Bootstrap class

  if ($this->wrapperClass ?? false) {
    $wrapperClass = $this->wrapperClass . ' dropdown'; // Bootstrap class
  }

  $toggleTag = 'a';
  $toggleAttrs = $this->toggleAttrs ?? [];
  $toggleAttrs['class'] = 'nav-link dropdown-toggle'; // Bootstrap class

  // An anchor tag with an href should only be used as
  // a non-js fallback to open the menu on another page
  if ($this->href ?? false) {
      $toggleAttrs['href'] = $this->href;
  }

  $toggleAttrs['role'] = 'button';
  $toggleAttrs['data-bs-toggle'] = 'dropdown'; // Bootstrap data-attr
?>

<?php ob_start(); ?>
  <ul class="dropdown-menu">
    <?php foreach ($this->menuItems as $current): ?>
      <li>
        <a class="dropdown-item<?php if ($current['selected'] ?? false): ?> active<?php endif ?>" href="<?=$this->escapeHtmlAttr($current['url']) ?>" rel="nofollow">
          <?=$this->transEsc($current['label']) ?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>

  <?=$this
      ->makeTag(
          tagName: $toggleTag,
          contents: $this->transEsc($this->toggleLabel),
          attrs: $toggleAttrs,
          options: ['escapeContent' => false]
      )
  ?>
<?php $menuContents = ob_get_contents(); ?>
<?php ob_end_clean(); ?>

<?=$this->makeTag($wrapperTag, $menuContents, $wrapperClass, ['escapeContent' => false]) ?>
