<?php
  $addThis = $this->addThis();
  if (!empty($addThis)) {
    $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
  }
?>
<nav class="record-nav" aria-label="<?=$this->transEscAttr('ajaxview_label_tools'); ?>">
  <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    <?php if (count($this->driver->getCitationFormats()) > 0): ?>
      <div class="btn-group me-1" role="group" aria-label="Group">
        <a class="btn btn-secondary cite-record" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Cite'))?>" rel="nofollow">
          <?=$this->icon('cite') ?>
          <?=$this->transEsc('Cite this')?>
        </a>
      </div>
    <?php endif; ?>

    <?php if ($this->accountCapabilities()->getSmsSetting() !== 'disabled'): ?>
      <div class="btn-group me-1" role="group" aria-label="Group">
        <a class="btn btn-secondary sms-record" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'SMS'))?>" rel="nofollow">
          <?=$this->icon('send-sms') ?>
          <?=$this->transEsc('Text this')?>
        </a>
      </div>
    <?php endif; ?>

    <div class="btn-group me-1" role="group" aria-label="Group">
      <a class="btn btn-secondary mail-record" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Email'))?>" rel="nofollow">
        <?=$this->icon('send-email') ?>
        <?=$this->transEsc('Email this')?>
      </a>
    </div>

    <div class="btn-group me-1" role="group" aria-label="Group">
      <a class="btn btn-secondary print-record" href="<?=$this->url()->addQueryParameters(['print' => true])?>" rel="nofollow">
        <?=$this->icon('print') ?>
        <?=$this->transEsc('Print')?>
      </a>
    </div>

    <?php $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
    <?php if (count($exportFormats) > 0): ?>
      <div class="btn-group me-1" role="group" aria-label="Group">
        <a class="btn btn-secondary export-toggle dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Export', [], '', ['excludeSearchId' => true]))?>" rel="nofollow" aria-expanded="false" aria-controls="export-options">
          <?=$this->icon('export') ?>
          <?=$this->transEsc('Export Record') ?>
        </a>
        <ul class="dropdown-menu" id="export-options" role="menu">
          <?php foreach ($exportFormats as $exportFormat): ?>
            <li>
              <a class="dropdown-item" <?php if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <?php endif; ?>href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Export', [], '', ['excludeSearchId' => true]))?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow" role="menuitem">
                <?=$this->transEsc('Export to')?> <?=$this->transEsc($this->export()->getLabelForFormat($exportFormat))?>
              </a>
            </li>
          <?php endforeach; ?>
        </ul>
      </div>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <div class="btn-group me-1" role="group" aria-label="Group">
        <?php if ($this->permission()->allowDisplay('feature.Favorites')): ?>
          <a class="btn btn-secondary save-record" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Save'))?>" rel="nofollow">
            <?=$this->icon('user-favorites') ?>
            <?=$this->transEsc('Add to favorites')?>
          </a>
        <?php elseif ($block = $this->permission()->getAlternateContent('feature.Favorites')): ?>
          <?=$block ?>
        <?php endif; ?>
      </div>
    <?php endif; ?>

    <?php if (!empty($addThis)): ?>
      <div class="btn-group me-1" role="group" aria-label="Group">
        <a class="btn btn-secondary addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>">
          <?=$this->icon('addthis-bookmark') ?>
          <?=$this->transEsc('Bookmark')?>
        </a>
      </div>
    <?php endif; ?>

    <?php if ($this->cart()->isActive()): ?>
      <div class="btn-group me-1" role="group" aria-label="Group">
        <?=$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier()]); ?>
      </div>
    <?php endif; ?>

    <div class="btn-group me-1" role="group" aria-label="Group">
      <a class="btn btn-secondary permalink-record" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Permalink'))?>" rel="nofollow">
        <?=$this->icon('external-link') ?>
        <?=$this->transEsc('permanent_link')?>
      </a>
    </div>
  </div>
</nav>
